name: librascal

on:
  push:
    branches: [main]
  schedule:
    # run at 10:00 every day
    - cron: '0 10 * * *'
  pull_request:
    # Check all PR

jobs:
  check-new-commits:
    runs-on: ubuntu-latest
    outputs:
      n_commits: ${{ steps.check-commits.outputs.n_commits }}
    steps:
      - name: clone librascal
        uses: actions/checkout@v3
        with:
          repository: lab-cosmo/librascal

      - id: check-commits
        name: check for recent commits
        run: echo "n_commits=$(git log --oneline --since='24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  build-wheels:
    needs: check-new-commits
    # build wheels on PR or if there are new commits
    if: ${{ needs.check-new-commits.outputs.n_commits > 0 || github.event_name == 'pull_request' }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python:
          - cp37
          - cp38
          - cp39
          - cp310
          # This does not build, it requires a pybind11 update on librascal side
          # - cp311

    steps:
      - name: clone librascal
        uses: actions/checkout@v3
        with:
          repository: lab-cosmo/librascal

      - uses: actions/setup-python@v3

      - name: install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD_VERBOSITY: 2
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: |
            delocate-wheel --ignore-missing-dependencies --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: |
            auditwheel repair --exclude librascal.so -w {dest_dir} {wheel}

      - name: upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            wheelhouse/*.whl
            wheelhouse/*.tar.gz

  update-gh-pages:
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: rascal

      - name: create index file
        run: python create-index.py rascal | tee rascal/index.html

      - name: deploy to gh-pages
        # only deploy from schedule/push to main branch
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rascal
          destination_dir: rascal
